// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgxcyhxclnrarcndvibc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtneGN5aHhjbG5yYXJjbmR2aWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDY4NjgsImV4cCI6MjA3MTU4Mjg2OH0.w4HPwgs0f9OGCBGxTKiKsW6iIhbEMbFkPuFVnLu2Ang";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});